// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: message.proto

#define INTERNAL_SUPPRESS_PROTOBUF_FIELD_DEPRECATION
#include "message.pb.h"

#include <algorithm>

#include <google/protobuf/stubs/common.h>
#include <google/protobuf/stubs/port.h>
#include <google/protobuf/stubs/once.h>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/wire_format_lite_inl.h>
#include <google/protobuf/descriptor.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/reflection_ops.h>
#include <google/protobuf/wire_format.h>
// @@protoc_insertion_point(includes)

namespace {

const ::google::protobuf::Descriptor* PrexMessage_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  PrexMessage_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* PrexMessage_MessageType_descriptor_ = NULL;
const ::google::protobuf::Descriptor* LoadProgram_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  LoadProgram_reflection_ = NULL;
const ::google::protobuf::Descriptor* Io_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Io_reflection_ = NULL;
const ::google::protobuf::EnumDescriptor* Io_FD_descriptor_ = NULL;
const ::google::protobuf::Descriptor* Image_descriptor_ = NULL;
const ::google::protobuf::internal::GeneratedMessageReflection*
  Image_reflection_ = NULL;

}  // namespace


void protobuf_AssignDesc_message_2eproto() {
  protobuf_AddDesc_message_2eproto();
  const ::google::protobuf::FileDescriptor* file =
    ::google::protobuf::DescriptorPool::generated_pool()->FindFileByName(
      "message.proto");
  GOOGLE_CHECK(file != NULL);
  PrexMessage_descriptor_ = file->message_type(0);
  static const int PrexMessage_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PrexMessage, type_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PrexMessage, payload_),
  };
  PrexMessage_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      PrexMessage_descriptor_,
      PrexMessage::default_instance_,
      PrexMessage_offsets_,
      -1,
      -1,
      -1,
      sizeof(PrexMessage),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PrexMessage, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(PrexMessage, _is_default_instance_));
  PrexMessage_MessageType_descriptor_ = PrexMessage_descriptor_->enum_type(0);
  LoadProgram_descriptor_ = file->message_type(1);
  static const int LoadProgram_offsets_[4] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LoadProgram, filename_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LoadProgram, code_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LoadProgram, argv_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LoadProgram, interpreter_),
  };
  LoadProgram_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      LoadProgram_descriptor_,
      LoadProgram::default_instance_,
      LoadProgram_offsets_,
      -1,
      -1,
      -1,
      sizeof(LoadProgram),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LoadProgram, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(LoadProgram, _is_default_instance_));
  Io_descriptor_ = file->message_type(2);
  static const int Io_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Io, type_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Io, data_),
  };
  Io_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      Io_descriptor_,
      Io::default_instance_,
      Io_offsets_,
      -1,
      -1,
      -1,
      sizeof(Io),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Io, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Io, _is_default_instance_));
  Io_FD_descriptor_ = Io_descriptor_->enum_type(0);
  Image_descriptor_ = file->message_type(3);
  static const int Image_offsets_[2] = {
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Image, payload_),
    GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Image, format_),
  };
  Image_reflection_ =
    ::google::protobuf::internal::GeneratedMessageReflection::NewGeneratedMessageReflection(
      Image_descriptor_,
      Image::default_instance_,
      Image_offsets_,
      -1,
      -1,
      -1,
      sizeof(Image),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Image, _internal_metadata_),
      GOOGLE_PROTOBUF_GENERATED_MESSAGE_FIELD_OFFSET(Image, _is_default_instance_));
}

namespace {

GOOGLE_PROTOBUF_DECLARE_ONCE(protobuf_AssignDescriptors_once_);
inline void protobuf_AssignDescriptorsOnce() {
  ::google::protobuf::GoogleOnceInit(&protobuf_AssignDescriptors_once_,
                 &protobuf_AssignDesc_message_2eproto);
}

void protobuf_RegisterTypes(const ::std::string&) {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      PrexMessage_descriptor_, &PrexMessage::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      LoadProgram_descriptor_, &LoadProgram::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      Io_descriptor_, &Io::default_instance());
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedMessage(
      Image_descriptor_, &Image::default_instance());
}

}  // namespace

void protobuf_ShutdownFile_message_2eproto() {
  delete PrexMessage::default_instance_;
  delete PrexMessage_reflection_;
  delete LoadProgram::default_instance_;
  delete LoadProgram_reflection_;
  delete Io::default_instance_;
  delete Io_reflection_;
  delete Image::default_instance_;
  delete Image_reflection_;
}

void protobuf_AddDesc_message_2eproto() {
  static bool already_here = false;
  if (already_here) return;
  already_here = true;
  GOOGLE_PROTOBUF_VERIFY_VERSION;

  ::google::protobuf::DescriptorPool::InternalAddGeneratedFile(
    "\n\rmessage.proto\"\251\001\n\013PrexMessage\022&\n\004type\030"
    "\001 \001(\0162\030.PrexMessage.MessageType\022\017\n\007paylo"
    "ad\030\002 \001(\014\"a\n\013MessageType\022\020\n\014LOAD_PROGRAM\020"
    "\000\022\006\n\002IO\020\001\022\t\n\005IMAGE\020\002\022\r\n\tTERMINATE\020\003\022\021\n\rT"
    "ERMINATE_ALL\020\004\022\013\n\007VERSION\020\005\"P\n\013LoadProgr"
    "am\022\020\n\010filename\030\001 \001(\t\022\014\n\004code\030\002 \001(\t\022\014\n\004ar"
    "gv\030\003 \003(\t\022\023\n\013interpreter\030\004 \001(\t\"Q\n\002Io\022\024\n\004t"
    "ype\030\001 \001(\0162\006.Io.FD\022\014\n\004data\030\002 \001(\014\"\'\n\002FD\022\t\n"
    "\005STDIN\020\000\022\n\n\006STDOUT\020\001\022\n\n\006STDERR\020\002\"(\n\005Imag"
    "e\022\017\n\007payload\030\001 \001(\014\022\016\n\006format\030\002 \001(\tb\006prot"
    "o3", 402);
  ::google::protobuf::MessageFactory::InternalRegisterGeneratedFile(
    "message.proto", &protobuf_RegisterTypes);
  PrexMessage::default_instance_ = new PrexMessage();
  LoadProgram::default_instance_ = new LoadProgram();
  Io::default_instance_ = new Io();
  Image::default_instance_ = new Image();
  PrexMessage::default_instance_->InitAsDefaultInstance();
  LoadProgram::default_instance_->InitAsDefaultInstance();
  Io::default_instance_->InitAsDefaultInstance();
  Image::default_instance_->InitAsDefaultInstance();
  ::google::protobuf::internal::OnShutdown(&protobuf_ShutdownFile_message_2eproto);
}

// Force AddDescriptors() to be called at static initialization time.
struct StaticDescriptorInitializer_message_2eproto {
  StaticDescriptorInitializer_message_2eproto() {
    protobuf_AddDesc_message_2eproto();
  }
} static_descriptor_initializer_message_2eproto_;

namespace {

static void MergeFromFail(int line) GOOGLE_ATTRIBUTE_COLD;
static void MergeFromFail(int line) {
  GOOGLE_CHECK(false) << __FILE__ << ":" << line;
}

}  // namespace


// ===================================================================

const ::google::protobuf::EnumDescriptor* PrexMessage_MessageType_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return PrexMessage_MessageType_descriptor_;
}
bool PrexMessage_MessageType_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
    case 3:
    case 4:
    case 5:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const PrexMessage_MessageType PrexMessage::LOAD_PROGRAM;
const PrexMessage_MessageType PrexMessage::IO;
const PrexMessage_MessageType PrexMessage::IMAGE;
const PrexMessage_MessageType PrexMessage::TERMINATE;
const PrexMessage_MessageType PrexMessage::TERMINATE_ALL;
const PrexMessage_MessageType PrexMessage::VERSION;
const PrexMessage_MessageType PrexMessage::MessageType_MIN;
const PrexMessage_MessageType PrexMessage::MessageType_MAX;
const int PrexMessage::MessageType_ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int PrexMessage::kTypeFieldNumber;
const int PrexMessage::kPayloadFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

PrexMessage::PrexMessage()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:PrexMessage)
}

void PrexMessage::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

PrexMessage::PrexMessage(const PrexMessage& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:PrexMessage)
}

void PrexMessage::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  type_ = 0;
  payload_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

PrexMessage::~PrexMessage() {
  // @@protoc_insertion_point(destructor:PrexMessage)
  SharedDtor();
}

void PrexMessage::SharedDtor() {
  payload_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void PrexMessage::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* PrexMessage::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return PrexMessage_descriptor_;
}

const PrexMessage& PrexMessage::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_message_2eproto();
  return *default_instance_;
}

PrexMessage* PrexMessage::default_instance_ = NULL;

PrexMessage* PrexMessage::New(::google::protobuf::Arena* arena) const {
  PrexMessage* n = new PrexMessage;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void PrexMessage::Clear() {
// @@protoc_insertion_point(message_clear_start:PrexMessage)
  type_ = 0;
  payload_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

bool PrexMessage::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:PrexMessage)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .PrexMessage.MessageType type = 1;
      case 1: {
        if (tag == 8) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_type(static_cast< ::PrexMessage_MessageType >(value));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_payload;
        break;
      }

      // optional bytes payload = 2;
      case 2: {
        if (tag == 18) {
         parse_payload:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_payload()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:PrexMessage)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:PrexMessage)
  return false;
#undef DO_
}

void PrexMessage::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:PrexMessage)
  // optional .PrexMessage.MessageType type = 1;
  if (this->type() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->type(), output);
  }

  // optional bytes payload = 2;
  if (this->payload().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      2, this->payload(), output);
  }

  // @@protoc_insertion_point(serialize_end:PrexMessage)
}

::google::protobuf::uint8* PrexMessage::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:PrexMessage)
  // optional .PrexMessage.MessageType type = 1;
  if (this->type() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->type(), target);
  }

  // optional bytes payload = 2;
  if (this->payload().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        2, this->payload(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:PrexMessage)
  return target;
}

int PrexMessage::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:PrexMessage)
  int total_size = 0;

  // optional .PrexMessage.MessageType type = 1;
  if (this->type() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->type());
  }

  // optional bytes payload = 2;
  if (this->payload().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->payload());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void PrexMessage::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:PrexMessage)
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const PrexMessage* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const PrexMessage>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:PrexMessage)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:PrexMessage)
    MergeFrom(*source);
  }
}

void PrexMessage::MergeFrom(const PrexMessage& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:PrexMessage)
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from.type() != 0) {
    set_type(from.type());
  }
  if (from.payload().size() > 0) {

    payload_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.payload_);
  }
}

void PrexMessage::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:PrexMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void PrexMessage::CopyFrom(const PrexMessage& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:PrexMessage)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool PrexMessage::IsInitialized() const {

  return true;
}

void PrexMessage::Swap(PrexMessage* other) {
  if (other == this) return;
  InternalSwap(other);
}
void PrexMessage::InternalSwap(PrexMessage* other) {
  std::swap(type_, other->type_);
  payload_.Swap(&other->payload_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata PrexMessage::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = PrexMessage_descriptor_;
  metadata.reflection = PrexMessage_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// PrexMessage

// optional .PrexMessage.MessageType type = 1;
void PrexMessage::clear_type() {
  type_ = 0;
}
 ::PrexMessage_MessageType PrexMessage::type() const {
  // @@protoc_insertion_point(field_get:PrexMessage.type)
  return static_cast< ::PrexMessage_MessageType >(type_);
}
 void PrexMessage::set_type(::PrexMessage_MessageType value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:PrexMessage.type)
}

// optional bytes payload = 2;
void PrexMessage::clear_payload() {
  payload_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& PrexMessage::payload() const {
  // @@protoc_insertion_point(field_get:PrexMessage.payload)
  return payload_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void PrexMessage::set_payload(const ::std::string& value) {
  
  payload_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:PrexMessage.payload)
}
 void PrexMessage::set_payload(const char* value) {
  
  payload_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:PrexMessage.payload)
}
 void PrexMessage::set_payload(const void* value, size_t size) {
  
  payload_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:PrexMessage.payload)
}
 ::std::string* PrexMessage::mutable_payload() {
  
  // @@protoc_insertion_point(field_mutable:PrexMessage.payload)
  return payload_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* PrexMessage::release_payload() {
  // @@protoc_insertion_point(field_release:PrexMessage.payload)
  
  return payload_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void PrexMessage::set_allocated_payload(::std::string* payload) {
  if (payload != NULL) {
    
  } else {
    
  }
  payload_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), payload);
  // @@protoc_insertion_point(field_set_allocated:PrexMessage.payload)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int LoadProgram::kFilenameFieldNumber;
const int LoadProgram::kCodeFieldNumber;
const int LoadProgram::kArgvFieldNumber;
const int LoadProgram::kInterpreterFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

LoadProgram::LoadProgram()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:LoadProgram)
}

void LoadProgram::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

LoadProgram::LoadProgram(const LoadProgram& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:LoadProgram)
}

void LoadProgram::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  filename_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  code_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  interpreter_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

LoadProgram::~LoadProgram() {
  // @@protoc_insertion_point(destructor:LoadProgram)
  SharedDtor();
}

void LoadProgram::SharedDtor() {
  filename_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  code_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  interpreter_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void LoadProgram::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* LoadProgram::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return LoadProgram_descriptor_;
}

const LoadProgram& LoadProgram::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_message_2eproto();
  return *default_instance_;
}

LoadProgram* LoadProgram::default_instance_ = NULL;

LoadProgram* LoadProgram::New(::google::protobuf::Arena* arena) const {
  LoadProgram* n = new LoadProgram;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void LoadProgram::Clear() {
// @@protoc_insertion_point(message_clear_start:LoadProgram)
  filename_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  code_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  interpreter_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  argv_.Clear();
}

bool LoadProgram::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:LoadProgram)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional string filename = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_filename()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->filename().data(), this->filename().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "LoadProgram.filename"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_code;
        break;
      }

      // optional string code = 2;
      case 2: {
        if (tag == 18) {
         parse_code:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_code()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->code().data(), this->code().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "LoadProgram.code"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_argv;
        break;
      }

      // repeated string argv = 3;
      case 3: {
        if (tag == 26) {
         parse_argv:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->add_argv()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->argv(this->argv_size() - 1).data(),
            this->argv(this->argv_size() - 1).length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "LoadProgram.argv"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(26)) goto parse_argv;
        if (input->ExpectTag(34)) goto parse_interpreter;
        break;
      }

      // optional string interpreter = 4;
      case 4: {
        if (tag == 34) {
         parse_interpreter:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_interpreter()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->interpreter().data(), this->interpreter().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "LoadProgram.interpreter"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:LoadProgram)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:LoadProgram)
  return false;
#undef DO_
}

void LoadProgram::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:LoadProgram)
  // optional string filename = 1;
  if (this->filename().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->filename().data(), this->filename().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "LoadProgram.filename");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      1, this->filename(), output);
  }

  // optional string code = 2;
  if (this->code().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->code().data(), this->code().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "LoadProgram.code");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->code(), output);
  }

  // repeated string argv = 3;
  for (int i = 0; i < this->argv_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->argv(i).data(), this->argv(i).length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "LoadProgram.argv");
    ::google::protobuf::internal::WireFormatLite::WriteString(
      3, this->argv(i), output);
  }

  // optional string interpreter = 4;
  if (this->interpreter().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->interpreter().data(), this->interpreter().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "LoadProgram.interpreter");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      4, this->interpreter(), output);
  }

  // @@protoc_insertion_point(serialize_end:LoadProgram)
}

::google::protobuf::uint8* LoadProgram::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:LoadProgram)
  // optional string filename = 1;
  if (this->filename().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->filename().data(), this->filename().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "LoadProgram.filename");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        1, this->filename(), target);
  }

  // optional string code = 2;
  if (this->code().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->code().data(), this->code().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "LoadProgram.code");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->code(), target);
  }

  // repeated string argv = 3;
  for (int i = 0; i < this->argv_size(); i++) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->argv(i).data(), this->argv(i).length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "LoadProgram.argv");
    target = ::google::protobuf::internal::WireFormatLite::
      WriteStringToArray(3, this->argv(i), target);
  }

  // optional string interpreter = 4;
  if (this->interpreter().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->interpreter().data(), this->interpreter().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "LoadProgram.interpreter");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        4, this->interpreter(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:LoadProgram)
  return target;
}

int LoadProgram::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:LoadProgram)
  int total_size = 0;

  // optional string filename = 1;
  if (this->filename().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->filename());
  }

  // optional string code = 2;
  if (this->code().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->code());
  }

  // optional string interpreter = 4;
  if (this->interpreter().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->interpreter());
  }

  // repeated string argv = 3;
  total_size += 1 * this->argv_size();
  for (int i = 0; i < this->argv_size(); i++) {
    total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
      this->argv(i));
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void LoadProgram::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:LoadProgram)
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const LoadProgram* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const LoadProgram>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:LoadProgram)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:LoadProgram)
    MergeFrom(*source);
  }
}

void LoadProgram::MergeFrom(const LoadProgram& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:LoadProgram)
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  argv_.MergeFrom(from.argv_);
  if (from.filename().size() > 0) {

    filename_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.filename_);
  }
  if (from.code().size() > 0) {

    code_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.code_);
  }
  if (from.interpreter().size() > 0) {

    interpreter_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.interpreter_);
  }
}

void LoadProgram::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:LoadProgram)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void LoadProgram::CopyFrom(const LoadProgram& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:LoadProgram)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool LoadProgram::IsInitialized() const {

  return true;
}

void LoadProgram::Swap(LoadProgram* other) {
  if (other == this) return;
  InternalSwap(other);
}
void LoadProgram::InternalSwap(LoadProgram* other) {
  filename_.Swap(&other->filename_);
  code_.Swap(&other->code_);
  argv_.UnsafeArenaSwap(&other->argv_);
  interpreter_.Swap(&other->interpreter_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata LoadProgram::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = LoadProgram_descriptor_;
  metadata.reflection = LoadProgram_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// LoadProgram

// optional string filename = 1;
void LoadProgram::clear_filename() {
  filename_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& LoadProgram::filename() const {
  // @@protoc_insertion_point(field_get:LoadProgram.filename)
  return filename_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void LoadProgram::set_filename(const ::std::string& value) {
  
  filename_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:LoadProgram.filename)
}
 void LoadProgram::set_filename(const char* value) {
  
  filename_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:LoadProgram.filename)
}
 void LoadProgram::set_filename(const char* value, size_t size) {
  
  filename_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:LoadProgram.filename)
}
 ::std::string* LoadProgram::mutable_filename() {
  
  // @@protoc_insertion_point(field_mutable:LoadProgram.filename)
  return filename_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* LoadProgram::release_filename() {
  // @@protoc_insertion_point(field_release:LoadProgram.filename)
  
  return filename_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void LoadProgram::set_allocated_filename(::std::string* filename) {
  if (filename != NULL) {
    
  } else {
    
  }
  filename_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), filename);
  // @@protoc_insertion_point(field_set_allocated:LoadProgram.filename)
}

// optional string code = 2;
void LoadProgram::clear_code() {
  code_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& LoadProgram::code() const {
  // @@protoc_insertion_point(field_get:LoadProgram.code)
  return code_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void LoadProgram::set_code(const ::std::string& value) {
  
  code_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:LoadProgram.code)
}
 void LoadProgram::set_code(const char* value) {
  
  code_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:LoadProgram.code)
}
 void LoadProgram::set_code(const char* value, size_t size) {
  
  code_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:LoadProgram.code)
}
 ::std::string* LoadProgram::mutable_code() {
  
  // @@protoc_insertion_point(field_mutable:LoadProgram.code)
  return code_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* LoadProgram::release_code() {
  // @@protoc_insertion_point(field_release:LoadProgram.code)
  
  return code_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void LoadProgram::set_allocated_code(::std::string* code) {
  if (code != NULL) {
    
  } else {
    
  }
  code_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), code);
  // @@protoc_insertion_point(field_set_allocated:LoadProgram.code)
}

// repeated string argv = 3;
int LoadProgram::argv_size() const {
  return argv_.size();
}
void LoadProgram::clear_argv() {
  argv_.Clear();
}
 const ::std::string& LoadProgram::argv(int index) const {
  // @@protoc_insertion_point(field_get:LoadProgram.argv)
  return argv_.Get(index);
}
 ::std::string* LoadProgram::mutable_argv(int index) {
  // @@protoc_insertion_point(field_mutable:LoadProgram.argv)
  return argv_.Mutable(index);
}
 void LoadProgram::set_argv(int index, const ::std::string& value) {
  // @@protoc_insertion_point(field_set:LoadProgram.argv)
  argv_.Mutable(index)->assign(value);
}
 void LoadProgram::set_argv(int index, const char* value) {
  argv_.Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:LoadProgram.argv)
}
 void LoadProgram::set_argv(int index, const char* value, size_t size) {
  argv_.Mutable(index)->assign(
    reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:LoadProgram.argv)
}
 ::std::string* LoadProgram::add_argv() {
  // @@protoc_insertion_point(field_add_mutable:LoadProgram.argv)
  return argv_.Add();
}
 void LoadProgram::add_argv(const ::std::string& value) {
  argv_.Add()->assign(value);
  // @@protoc_insertion_point(field_add:LoadProgram.argv)
}
 void LoadProgram::add_argv(const char* value) {
  argv_.Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:LoadProgram.argv)
}
 void LoadProgram::add_argv(const char* value, size_t size) {
  argv_.Add()->assign(reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:LoadProgram.argv)
}
 const ::google::protobuf::RepeatedPtrField< ::std::string>&
LoadProgram::argv() const {
  // @@protoc_insertion_point(field_list:LoadProgram.argv)
  return argv_;
}
 ::google::protobuf::RepeatedPtrField< ::std::string>*
LoadProgram::mutable_argv() {
  // @@protoc_insertion_point(field_mutable_list:LoadProgram.argv)
  return &argv_;
}

// optional string interpreter = 4;
void LoadProgram::clear_interpreter() {
  interpreter_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& LoadProgram::interpreter() const {
  // @@protoc_insertion_point(field_get:LoadProgram.interpreter)
  return interpreter_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void LoadProgram::set_interpreter(const ::std::string& value) {
  
  interpreter_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:LoadProgram.interpreter)
}
 void LoadProgram::set_interpreter(const char* value) {
  
  interpreter_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:LoadProgram.interpreter)
}
 void LoadProgram::set_interpreter(const char* value, size_t size) {
  
  interpreter_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:LoadProgram.interpreter)
}
 ::std::string* LoadProgram::mutable_interpreter() {
  
  // @@protoc_insertion_point(field_mutable:LoadProgram.interpreter)
  return interpreter_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* LoadProgram::release_interpreter() {
  // @@protoc_insertion_point(field_release:LoadProgram.interpreter)
  
  return interpreter_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void LoadProgram::set_allocated_interpreter(::std::string* interpreter) {
  if (interpreter != NULL) {
    
  } else {
    
  }
  interpreter_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), interpreter);
  // @@protoc_insertion_point(field_set_allocated:LoadProgram.interpreter)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

const ::google::protobuf::EnumDescriptor* Io_FD_descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Io_FD_descriptor_;
}
bool Io_FD_IsValid(int value) {
  switch(value) {
    case 0:
    case 1:
    case 2:
      return true;
    default:
      return false;
  }
}

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const Io_FD Io::STDIN;
const Io_FD Io::STDOUT;
const Io_FD Io::STDERR;
const Io_FD Io::FD_MIN;
const Io_FD Io::FD_MAX;
const int Io::FD_ARRAYSIZE;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900
#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Io::kTypeFieldNumber;
const int Io::kDataFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Io::Io()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:Io)
}

void Io::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

Io::Io(const Io& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:Io)
}

void Io::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  type_ = 0;
  data_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

Io::~Io() {
  // @@protoc_insertion_point(destructor:Io)
  SharedDtor();
}

void Io::SharedDtor() {
  data_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void Io::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Io::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Io_descriptor_;
}

const Io& Io::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_message_2eproto();
  return *default_instance_;
}

Io* Io::default_instance_ = NULL;

Io* Io::New(::google::protobuf::Arena* arena) const {
  Io* n = new Io;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Io::Clear() {
// @@protoc_insertion_point(message_clear_start:Io)
  type_ = 0;
  data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

bool Io::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Io)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional .Io.FD type = 1;
      case 1: {
        if (tag == 8) {
          int value;
          DO_((::google::protobuf::internal::WireFormatLite::ReadPrimitive<
                   int, ::google::protobuf::internal::WireFormatLite::TYPE_ENUM>(
                 input, &value)));
          set_type(static_cast< ::Io_FD >(value));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_data;
        break;
      }

      // optional bytes data = 2;
      case 2: {
        if (tag == 18) {
         parse_data:
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_data()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Io)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Io)
  return false;
#undef DO_
}

void Io::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Io)
  // optional .Io.FD type = 1;
  if (this->type() != 0) {
    ::google::protobuf::internal::WireFormatLite::WriteEnum(
      1, this->type(), output);
  }

  // optional bytes data = 2;
  if (this->data().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      2, this->data(), output);
  }

  // @@protoc_insertion_point(serialize_end:Io)
}

::google::protobuf::uint8* Io::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:Io)
  // optional .Io.FD type = 1;
  if (this->type() != 0) {
    target = ::google::protobuf::internal::WireFormatLite::WriteEnumToArray(
      1, this->type(), target);
  }

  // optional bytes data = 2;
  if (this->data().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        2, this->data(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:Io)
  return target;
}

int Io::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:Io)
  int total_size = 0;

  // optional .Io.FD type = 1;
  if (this->type() != 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::EnumSize(this->type());
  }

  // optional bytes data = 2;
  if (this->data().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->data());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Io::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Io)
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const Io* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const Io>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Io)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Io)
    MergeFrom(*source);
  }
}

void Io::MergeFrom(const Io& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Io)
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from.type() != 0) {
    set_type(from.type());
  }
  if (from.data().size() > 0) {

    data_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.data_);
  }
}

void Io::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Io)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Io::CopyFrom(const Io& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Io)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Io::IsInitialized() const {

  return true;
}

void Io::Swap(Io* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Io::InternalSwap(Io* other) {
  std::swap(type_, other->type_);
  data_.Swap(&other->data_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Io::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Io_descriptor_;
  metadata.reflection = Io_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Io

// optional .Io.FD type = 1;
void Io::clear_type() {
  type_ = 0;
}
 ::Io_FD Io::type() const {
  // @@protoc_insertion_point(field_get:Io.type)
  return static_cast< ::Io_FD >(type_);
}
 void Io::set_type(::Io_FD value) {
  
  type_ = value;
  // @@protoc_insertion_point(field_set:Io.type)
}

// optional bytes data = 2;
void Io::clear_data() {
  data_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& Io::data() const {
  // @@protoc_insertion_point(field_get:Io.data)
  return data_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Io::set_data(const ::std::string& value) {
  
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Io.data)
}
 void Io::set_data(const char* value) {
  
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Io.data)
}
 void Io::set_data(const void* value, size_t size) {
  
  data_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Io.data)
}
 ::std::string* Io::mutable_data() {
  
  // @@protoc_insertion_point(field_mutable:Io.data)
  return data_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* Io::release_data() {
  // @@protoc_insertion_point(field_release:Io.data)
  
  return data_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Io::set_allocated_data(::std::string* data) {
  if (data != NULL) {
    
  } else {
    
  }
  data_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), data);
  // @@protoc_insertion_point(field_set_allocated:Io.data)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// ===================================================================

#if !defined(_MSC_VER) || _MSC_VER >= 1900
const int Image::kPayloadFieldNumber;
const int Image::kFormatFieldNumber;
#endif  // !defined(_MSC_VER) || _MSC_VER >= 1900

Image::Image()
  : ::google::protobuf::Message(), _internal_metadata_(NULL) {
  SharedCtor();
  // @@protoc_insertion_point(constructor:Image)
}

void Image::InitAsDefaultInstance() {
  _is_default_instance_ = true;
}

Image::Image(const Image& from)
  : ::google::protobuf::Message(),
    _internal_metadata_(NULL) {
  SharedCtor();
  MergeFrom(from);
  // @@protoc_insertion_point(copy_constructor:Image)
}

void Image::SharedCtor() {
    _is_default_instance_ = false;
  ::google::protobuf::internal::GetEmptyString();
  _cached_size_ = 0;
  payload_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  format_.UnsafeSetDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

Image::~Image() {
  // @@protoc_insertion_point(destructor:Image)
  SharedDtor();
}

void Image::SharedDtor() {
  payload_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  format_.DestroyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  if (this != default_instance_) {
  }
}

void Image::SetCachedSize(int size) const {
  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
}
const ::google::protobuf::Descriptor* Image::descriptor() {
  protobuf_AssignDescriptorsOnce();
  return Image_descriptor_;
}

const Image& Image::default_instance() {
  if (default_instance_ == NULL) protobuf_AddDesc_message_2eproto();
  return *default_instance_;
}

Image* Image::default_instance_ = NULL;

Image* Image::New(::google::protobuf::Arena* arena) const {
  Image* n = new Image;
  if (arena != NULL) {
    arena->Own(n);
  }
  return n;
}

void Image::Clear() {
// @@protoc_insertion_point(message_clear_start:Image)
  payload_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
  format_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}

bool Image::MergePartialFromCodedStream(
    ::google::protobuf::io::CodedInputStream* input) {
#define DO_(EXPRESSION) if (!GOOGLE_PREDICT_TRUE(EXPRESSION)) goto failure
  ::google::protobuf::uint32 tag;
  // @@protoc_insertion_point(parse_start:Image)
  for (;;) {
    ::std::pair< ::google::protobuf::uint32, bool> p = input->ReadTagWithCutoff(127);
    tag = p.first;
    if (!p.second) goto handle_unusual;
    switch (::google::protobuf::internal::WireFormatLite::GetTagFieldNumber(tag)) {
      // optional bytes payload = 1;
      case 1: {
        if (tag == 10) {
          DO_(::google::protobuf::internal::WireFormatLite::ReadBytes(
                input, this->mutable_payload()));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectTag(18)) goto parse_format;
        break;
      }

      // optional string format = 2;
      case 2: {
        if (tag == 18) {
         parse_format:
          DO_(::google::protobuf::internal::WireFormatLite::ReadString(
                input, this->mutable_format()));
          DO_(::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
            this->format().data(), this->format().length(),
            ::google::protobuf::internal::WireFormatLite::PARSE,
            "Image.format"));
        } else {
          goto handle_unusual;
        }
        if (input->ExpectAtEnd()) goto success;
        break;
      }

      default: {
      handle_unusual:
        if (tag == 0 ||
            ::google::protobuf::internal::WireFormatLite::GetTagWireType(tag) ==
            ::google::protobuf::internal::WireFormatLite::WIRETYPE_END_GROUP) {
          goto success;
        }
        DO_(::google::protobuf::internal::WireFormatLite::SkipField(input, tag));
        break;
      }
    }
  }
success:
  // @@protoc_insertion_point(parse_success:Image)
  return true;
failure:
  // @@protoc_insertion_point(parse_failure:Image)
  return false;
#undef DO_
}

void Image::SerializeWithCachedSizes(
    ::google::protobuf::io::CodedOutputStream* output) const {
  // @@protoc_insertion_point(serialize_start:Image)
  // optional bytes payload = 1;
  if (this->payload().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::WriteBytesMaybeAliased(
      1, this->payload(), output);
  }

  // optional string format = 2;
  if (this->format().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->format().data(), this->format().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Image.format");
    ::google::protobuf::internal::WireFormatLite::WriteStringMaybeAliased(
      2, this->format(), output);
  }

  // @@protoc_insertion_point(serialize_end:Image)
}

::google::protobuf::uint8* Image::SerializeWithCachedSizesToArray(
    ::google::protobuf::uint8* target) const {
  // @@protoc_insertion_point(serialize_to_array_start:Image)
  // optional bytes payload = 1;
  if (this->payload().size() > 0) {
    target =
      ::google::protobuf::internal::WireFormatLite::WriteBytesToArray(
        1, this->payload(), target);
  }

  // optional string format = 2;
  if (this->format().size() > 0) {
    ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
      this->format().data(), this->format().length(),
      ::google::protobuf::internal::WireFormatLite::SERIALIZE,
      "Image.format");
    target =
      ::google::protobuf::internal::WireFormatLite::WriteStringToArray(
        2, this->format(), target);
  }

  // @@protoc_insertion_point(serialize_to_array_end:Image)
  return target;
}

int Image::ByteSize() const {
// @@protoc_insertion_point(message_byte_size_start:Image)
  int total_size = 0;

  // optional bytes payload = 1;
  if (this->payload().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::BytesSize(
        this->payload());
  }

  // optional string format = 2;
  if (this->format().size() > 0) {
    total_size += 1 +
      ::google::protobuf::internal::WireFormatLite::StringSize(
        this->format());
  }

  GOOGLE_SAFE_CONCURRENT_WRITES_BEGIN();
  _cached_size_ = total_size;
  GOOGLE_SAFE_CONCURRENT_WRITES_END();
  return total_size;
}

void Image::MergeFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_merge_from_start:Image)
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  const Image* source = 
      ::google::protobuf::internal::DynamicCastToGenerated<const Image>(
          &from);
  if (source == NULL) {
  // @@protoc_insertion_point(generalized_merge_from_cast_fail:Image)
    ::google::protobuf::internal::ReflectionOps::Merge(from, this);
  } else {
  // @@protoc_insertion_point(generalized_merge_from_cast_success:Image)
    MergeFrom(*source);
  }
}

void Image::MergeFrom(const Image& from) {
// @@protoc_insertion_point(class_specific_merge_from_start:Image)
  if (GOOGLE_PREDICT_FALSE(&from == this)) MergeFromFail(__LINE__);
  if (from.payload().size() > 0) {

    payload_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.payload_);
  }
  if (from.format().size() > 0) {

    format_.AssignWithDefault(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), from.format_);
  }
}

void Image::CopyFrom(const ::google::protobuf::Message& from) {
// @@protoc_insertion_point(generalized_copy_from_start:Image)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

void Image::CopyFrom(const Image& from) {
// @@protoc_insertion_point(class_specific_copy_from_start:Image)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}

bool Image::IsInitialized() const {

  return true;
}

void Image::Swap(Image* other) {
  if (other == this) return;
  InternalSwap(other);
}
void Image::InternalSwap(Image* other) {
  payload_.Swap(&other->payload_);
  format_.Swap(&other->format_);
  _internal_metadata_.Swap(&other->_internal_metadata_);
  std::swap(_cached_size_, other->_cached_size_);
}

::google::protobuf::Metadata Image::GetMetadata() const {
  protobuf_AssignDescriptorsOnce();
  ::google::protobuf::Metadata metadata;
  metadata.descriptor = Image_descriptor_;
  metadata.reflection = Image_reflection_;
  return metadata;
}

#if PROTOBUF_INLINE_NOT_IN_HEADERS
// Image

// optional bytes payload = 1;
void Image::clear_payload() {
  payload_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& Image::payload() const {
  // @@protoc_insertion_point(field_get:Image.payload)
  return payload_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Image::set_payload(const ::std::string& value) {
  
  payload_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Image.payload)
}
 void Image::set_payload(const char* value) {
  
  payload_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Image.payload)
}
 void Image::set_payload(const void* value, size_t size) {
  
  payload_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Image.payload)
}
 ::std::string* Image::mutable_payload() {
  
  // @@protoc_insertion_point(field_mutable:Image.payload)
  return payload_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* Image::release_payload() {
  // @@protoc_insertion_point(field_release:Image.payload)
  
  return payload_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Image::set_allocated_payload(::std::string* payload) {
  if (payload != NULL) {
    
  } else {
    
  }
  payload_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), payload);
  // @@protoc_insertion_point(field_set_allocated:Image.payload)
}

// optional string format = 2;
void Image::clear_format() {
  format_.ClearToEmptyNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 const ::std::string& Image::format() const {
  // @@protoc_insertion_point(field_get:Image.format)
  return format_.GetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Image::set_format(const ::std::string& value) {
  
  format_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), value);
  // @@protoc_insertion_point(field_set:Image.format)
}
 void Image::set_format(const char* value) {
  
  format_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), ::std::string(value));
  // @@protoc_insertion_point(field_set_char:Image.format)
}
 void Image::set_format(const char* value, size_t size) {
  
  format_.SetNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(),
      ::std::string(reinterpret_cast<const char*>(value), size));
  // @@protoc_insertion_point(field_set_pointer:Image.format)
}
 ::std::string* Image::mutable_format() {
  
  // @@protoc_insertion_point(field_mutable:Image.format)
  return format_.MutableNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 ::std::string* Image::release_format() {
  // @@protoc_insertion_point(field_release:Image.format)
  
  return format_.ReleaseNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited());
}
 void Image::set_allocated_format(::std::string* format) {
  if (format != NULL) {
    
  } else {
    
  }
  format_.SetAllocatedNoArena(&::google::protobuf::internal::GetEmptyStringAlreadyInited(), format);
  // @@protoc_insertion_point(field_set_allocated:Image.format)
}

#endif  // PROTOBUF_INLINE_NOT_IN_HEADERS

// @@protoc_insertion_point(namespace_scope)

// @@protoc_insertion_point(global_scope)
